# Generated by Django 3.0.8 on 2020-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200903_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
