# Generated by Django 3.0.8 on 2020-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200911_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
