# Generated by Django 3.0.8 on 2020-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200911_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
