# Generated by Django 3.0.8 on 2020-09-12 16:22

from django.db import migrations, models
import network.models
import network.storage


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200912_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, storage=network.storage.OverwriteStorage(), upload_to=network.models.new_filename),
        ),
    ]
